import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header/Header";
import Sidebar from "@/components/Sidebar/Sidebar";
import { SidebarProvider } from "@/context/SidebarContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SidebarProvider>
          <div className="max-h-screen flex flex-col ">
            <Header />

            <div className="grid grid-cols-[auto,1fr] flex-grow-1 overflow-auto">
              <Sidebar />
              {children}
            </div>
          </div>
        </SidebarProvider>
      </body>
    </html>
  );
}
